# Generated by Django 4.1.1 on 2022-09-19 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=6, max_digits=21)),
                ('loan_term', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=6, max_digits=21)),
                ('loan_month', models.CharField(max_length=2)),
                ('loan_year', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('payment_amount', models.DecimalField(decimal_places=6, max_digits=21)),
                ('principal', models.DecimalField(decimal_places=6, max_digits=21)),
                ('interest', models.DecimalField(decimal_places=6, max_digits=21)),
                ('balance', models.DecimalField(decimal_places=6, max_digits=21)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanlist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='loanlist',
            constraint=models.CheckConstraint(check=models.Q(('loan_amount__gte', 1000), ('loan_amount__lte', 100000000)), name='Loan amount is valid between 1000 and 100,000,000 THB'),
        ),
        migrations.AddConstraint(
            model_name='loanlist',
            constraint=models.CheckConstraint(check=models.Q(('loan_term__gte', 1), ('loan_term__lte', 50)), name='Loan term is valid between 1 and 50 years'),
        ),
    ]
